- name: Install Java (for Jenkins)
  apt:
    name: openjdk-17-jdk
    state: present

- name: Download Jenkins GPG key
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
    mode: '0644'

- name: Add Jenkins APT repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/jenkins.list
    line: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/"
    create: yes

- name: Update apt packages
  apt:
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Start Jenkins service
  service:
    name: jenkins
    state: started
    enabled: yes

- name: Wait for Jenkins to become available
  wait_for:
    host: localhost
    port: 8080
    delay: 30
    timeout: 60

# Ensure Jenkins is running before accessing the password
- name: Check if Jenkins service is running
  service_facts:

- name: Retrieve Jenkins initial admin password and save to importance.txt on local machine
  ansible.builtin.command:
    cmd: cat /var/lib/jenkins/secrets/initialAdminPassword
  become: true
  register: jenkins_password
