flask:
  replicaCount: 1
  image:
    repository: lanirelad/contacts-manager
    tag: 0.9

mongo:
  replicaCount: 1
  image:
    repository: mongo
    tag: latest
  storage:
    size: 3Gi

mongo-express:
  replicaCount: 1
  image:
    repository: mongo-express
    tag: latest

mysql:
  replicaCount: 1
  image:
    repository: mysql
    tag: 5.7
  storage:
    size: 3Gi

grafana:
  enabled: true  # Ensure Grafana is enabled
  service:
    type: LoadBalancer  # Expose Grafana as LoadBalancer
    port: 3000           # External port for Grafana
    targetPort: 3000   # Grafana's internal port