flask:
  replicaCount: 1
  image:
    repository: lanirelad/contacts-manager
    tag: latest

mongo:
  replicaCount: 1
  image:
    repository: mongo
    tag: latest
  storage:
    size: 3Gi

mysql:
  replicaCount: 1
  image:
    repository: mysql
    tag: 5.7
  storage:
    size: 3Gi