# install the necessary tools to interact with AWS and EKS
# EKSCTL, AWS CLI

---
- name: Download and extract eksctl binary
  ansible.builtin.shell: |
    curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
  args:
    _uses_shell: true

- name: Move eksctl binary to /usr/local/bin
  ansible.builtin.command:
    cmd: mv /tmp/eksctl /usr/local/bin/eksctl
  become: true

- name: Verify eksctl installation
  ansible.builtin.command: eksctl version
  register: eksctl_version
  failed_when: eksctl_version.rc != 0

- name: Download aws-cli installer
  ansible.builtin.get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip
    mode: '0644'

- name: Create directory for AWS CLI extraction
  ansible.builtin.file:
    path: /tmp/aws-cli
    state: directory
    mode: '0755'

- name: Install unzip package (if required)
  ansible.builtin.package:
    name: unzip
    state: present

- name: Extract AWS CLI installer manually
  ansible.builtin.command:
    cmd: "unzip -o /tmp/awscliv2.zip -d /tmp/"
    creates: /tmp/aws

- name: Run AWS CLI installer
  ansible.builtin.command: /tmp/aws/install
  args:
    creates: /usr/local/bin/aws

- name: Verify aws-cli installation
  ansible.builtin.command: aws --version
  register: awscli_version
  failed_when: awscli_version.rc != 0
