# flask deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-contacts-app
  labels:
    app: flask-contacts-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-contacts-app
  template:
    metadata:
      labels:
        app: flask-contacts-app
    spec:
      containers:
      - name: flask-contacts-app
        image: lanirelad/contacts-manager:0.9
        ports:
        - containerPort: 5056
        command: ["python"]
        args: ["main.py"]
        env:
        # mongo test
        # - name: ME_CONFIG_MONGODB_ADMINUSERNAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: secret-dbs
        #       key: mongo-root-username
        # - name: ME_CONFIG_MONGODB_ADMINPASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: secret-dbs
        #       key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: flask-app-config
              key: MONGO_URI
        
        # which database to use            
        - name: DB_USAGE
          valueFrom:
            configMapKeyRef:
              name: flask-app-config
              key: DB_USAGE
        # mysql
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: flask-app-config
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: flask-app-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-dbs
              key: rootPass
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: flask-app-config
              key: DB_NAME
        - name: DB_TABLE
          valueFrom:
            configMapKeyRef:
              name: flask-app-config
              key: DB_TABLE
        # mongo
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: flask-app-config
              key: MONGO_URI
        - name: ARCHIVE
          valueFrom:
            configMapKeyRef:
              name: flask-app-config
              key: ARCHIVE
        - name: ARCHIVE_COL
          valueFrom:
            configMapKeyRef:
              name: flask-app-config
              key: ARCHIVE_COL
        - name: MANAGER
          valueFrom:
            configMapKeyRef:
              name: flask-app-config
              key: MANAGER
        - name: MANAGER_COL
          valueFrom:
            configMapKeyRef:
              name: flask-app-config
              key: MANAGER_COL
        - name: FAKE
          valueFrom:
            configMapKeyRef:
              name: flask-app-config
              key: FAKE
        - name: FAKE_COL
          valueFrom:
            configMapKeyRef:
              name: flask-app-config
              key: FAKE_COL
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
        - name: db-images
          mountPath: /workingDir/static/profileImages
      volumes:
      - name: db-images