apiVersion: v1
kind: Service
metadata:
  name: flask-contacts-app-service
spec:
  selector:
    app: flask-contacts-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5056
      targetPort: 5056