apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-app-config
data:
  DB_USAGE: "MONGO"
  MONGO_URI: "mongodb://mongo-service:27017/"
  DB_HOST: "mysql-service"
  DB_USER: "root"
  DB_NAME: "webpageusers"
  DB_TABLE: "users"