# Provision and configure the jenkins server and requirements for running the EKS

---
- hosts: jenkins-server
  become: yes
  vars_files:
    - roles/jenkins-config/vars/plugins.yml
  roles:
    - common
    - kubernetes
    - aws
    - helm
    - jenkins
    # - jenkins-config